- name: setup vp bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import vpc setup variable
      include_vars: vars/bastion_setup

    - name: Import vpc setup variable
      include_vars: vars/output_vars

    - name: create vp ec2 key
      ec2_key:
        name: vp-key
        region: "{{region}}"
      register: key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create security group for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all portbwithin sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
        register: BastionSG_out

    - creating Bastion Host
      ec2:
        key_name: vp-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        istance_tags:
          Name: "Bastion_host"
          Project: vp
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: vp
          Owner: Devops Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out



